server:
  port: 8888
spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/willenleiros/config-repo.git
          username: email
          password: senha
          basedir: ~/tmp
          delete-untracked-branches: true
          defaultLabel: main